# Generated by Django 3.1.2 on 2020-10-05 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Tag title')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'db_table': 'TAG',
            },
        ),
        migrations.CreateModel(
            name='TextSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this should be treated as deleted or not. ', verbose_name='Is deleted')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='text_snippet.tag')),
            ],
            options={
                'verbose_name': 'text_snippet',
                'verbose_name_plural': 'texts',
                'db_table': 'TEXT',
            },
        ),
    ]
