# Generated by Django 3.1.2 on 2020-10-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_snippet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsnippet',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
